
// Filter()...

let my_array=[1,2,3,4,5,6,7,8,9,0];
const new_array=my_array.filter((num)=>num>4);//For single Line...
console.log(new_array);

const new_array2=my_array.filter((num)=>{  // For multi Line...
    return num>4;
})
console.log(new_array2);

// Reduce()...   //we use reduce method to reduce whole array into an single value...

let arr=[1,2,3,4,5];
// initial_value=0;
const sum=arr.reduce((accumulator,curruntvalue)=> //accumulator->firstly take initialvalue 0 then value like 1st->0,2nd->0+1=1,3rd->1+2=3...
accumulator+curruntvalue,0);                     //currentvalue->is values of an array...
console.log(sum);                                //Its our choice give initialvalue with decleration or without decleration...